import 'dart:io';

import 'package:flutter/widgets.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  final File resultFile = File('probe_result.txt');

  try {
    // This mirrors the platform condition generated by plugin_ffi before the
    // later Platform.isWindows branch is reached.
    final bool sharedObjectBranch =
        Platform.isAndroid || Platform.isLinux || Platform.isOhos;

    resultFile.writeAsStringSync(
      [
        'status=ok',
        'operatingSystem=${Platform.operatingSystem}',
        'isWindows=${Platform.isWindows}',
        'sharedObjectBranch=$sharedObjectBranch',
      ].join('\n'),
    );
    exit(0);
  } catch (error, stackTrace) {
    resultFile.writeAsStringSync(
      [
        'status=error',
        'operatingSystem=${Platform.operatingSystem}',
        'isWindows=${Platform.isWindows}',
        'error=$error',
        'stack=$stackTrace',
      ].join('\n'),
    );
    exit(42);
  }
}
